name: Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decode Firebase service account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload to Firebase App Distribution
        run: |
          ./gradlew appDistributionUploadDebug \
            --firebaseAppId="1:362267466547:android:f89e76782ee6b616b2bc46" \
            --serviceCredentialsFile=service-account.json \
            --groups=qa